# Alias defenitions

# apt update and upgrade
alias yay='sudo apt update && sudo apt upgrade'

# purge an installed package
alias yeet='sudo apt remove --purge'

# copy with a progress bar using rsync
alias dup='rsync -ah --info=progress2'

# move to trash
alias waste='mv --force -t ~/.local/share/Trash/files'

# search for packages
alias evida='apt search --names-only'

# run previos command as sudo
alias fuck='sudo $(fc -ln -1)'
